### ISSUE TITLE
ENABLE_CROSSPLAY and DISABLE_BATTLEYE not listed in wiki

### ISSUE THREAD

**Issue by ThePowershellNinja** [Hermsi1337/docker-ark-server#24]
I have been looking for a way to disable battleye in your container, and I came across lines 50-55 in the entrypoint.sh. It seems like you support the ENABLE_CROSSPLAY and DISABLE_BATTLEYE environment variables but they are not documented in your markdown anywhere. Please add!

While we are on the topic, can you add support for -UseAllAvailableCores?

**Comment by jstnmthw** [comment]
They were added in the inital pull request #23.

**Comment by Hermsi1337** [comment]
Hey @ThePowershellNinja,

as @jstnmthw stated, the docs were added in the mentioned PR.

Is there something missing you'd also like to see in the `README` ?   
Let me know if yes (:

Regards

**Comment by ThePowershellNinja** [comment]
The lines added in that PR look perfect! Thanks!

Also, do you guys mind if I contribute to the project? I see some places where I can help! Im a DevOps engineer who is mostly Windows based, but I know my way around Linux pretty well. I would like to help add functionality, similar to how these two server flags were enabled. It looks like you don't allow users to specify their own arkmanager.cfg, intentionally or not. I could bring a lot to the table I think.

**Comment by Hermsi1337** [comment]
Sure - that would be awesome.

I built the first version of this image quite some time ago when I was playing Ark.  
Since I quitted Ark, I did not update this image. There's a lot of stuff todo.

Also, `arkmanager` received a lot of updates which I'm not fully aware of (tbh).   

I'm currently working on a major refactoring of this image, including a custom arkmanager config.  
I will push it in an additional branch in order for you to have a look at it. I'd appreciate your feedback on it!

Many thanks.
