### ISSUE TITLE
Fix format of custom flags passed to the server binary

### ISSUE THREAD

**Issue by ThePowershellNinja** [Hermsi1337/docker-ark-server#29]
I found the first thing I want to work on.

When I include the new environment variables for enable crossplay and/or nobattleye, It is plugged into the server command line incorrectly. It technically works, but it is not what you would expect. See below:
![image](https://user-images.githubusercontent.com/6169890/147836723-a1655c23-c50e-4927-88ec-8a9eb7f3bb26.png)

I want to fix this so that you only see `-NoBattlEye` and not `-NoBattlEye=-NoBattlEye`.

**Comment by ThePowershellNinja** [comment]
One thing that I notice is that the arkmanager.cfg makes absolutely no impact what so ever. Only edits to the `arkmanager-user.cfg` located in the container with the name `/etc/arkmanager/instances/main.cfg`  make it to the server instance. Seems like the work done at the entry point to copy `arkmanager.cfg` to templates, and then again to the root of `/app` might be pointless?

**Comment by ThePowershellNinja** [comment]
I cannot get this to act right no matter what I try.  I suspect that this is a bug in the arkmanager application.

I opened https://github.com/arkmanager/ark-server-tools/issues/1211 on their github project.

**Comment by DACRepair** [comment]
So this is an issue with ark-server-tools. It is an issue with the `-arkopt,` directive. Theoretically any flag can be set to a value other than null, and it will be enabled. If it were to be cleaned up, you might want to change it to `--arkopt,-NoBattlEye='true'` just to it _looks_ nice. As far as the functionality goes, as long as a flag is set to anything, it is "enabled" so it does work.

**Comment by Hermsi1337** [comment]
With #25 users can provide their own `arkmanager`-config. So there is technically no need to use the environment-flags in order to get these options appended to the server-command.

I'll leave this issue open so we can track the progress of https://github.com/arkmanager/ark-server-tools/issues/1211

Another possible "fix" coming to my mind is using some sort of templating like `go`-templates in order to render a proper config with the required opts.   
Something like the env `ARKFLAG_NO_BATTLE_EYE` becomes `arkflag_NoBattleEye=true` in the `arkmanager.cfg`.    
Implementing such a rendering would result in a fresh-generated config on every container restart. So we'd need some sort of "global" config which can be included and overriden by the instance-configs.

What do you think about that?

**Comment by ThePowershellNinja** [comment]
I think that is a good idea. I know that you can configure options in both the `/app/arkmanager/arkmanager.cfg` as well as `/app/arkmanager/instances/main.cfg` simultaneously. There might be some wiggle room there to specify things passed in by environment flag in one of them, with the expectation of the other config overwriting it with user defined settings. I'm not sure what the precedence looks like though. For the time being though, I think it would be a good idea to back off on the two flags that were implemented via environment variable in favor of a user defined config for now. I really like the idea of providing out of the box environment var options for the server flags though and I think that using environment variables to generate and over-writable config would be an ideal scenario.

**Comment by ThePowershellNinja** [comment]
This issue seems to have been resolved with the newest version of ark-server-tools v1.6.61. I tested and verified the fix.
![image](https://user-images.githubusercontent.com/6169890/148319497-9329316a-11f1-4fe5-9675-6f02fbb2e546.png)

**Comment by ThePowershellNinja** [comment]
@Hermsi1337 @halkeye @BloodWorkXGaming @suhaibmalik @DACRepair Given that this functionality is fixed, How do we want to proceed with this functionality? Do we want to expose environment var options for the different server flags? or do we want to back off of the two we already implemented and expect the user rely on the arkmanager.cfg for it?

If we choose to continue to support environment flags that are passed in with the container, then I plan on opening a new work item to implement the rest of the server flags.

**Comment by halkeye** [comment]
Sorry I havn't been around for the big refactors lately. This weekend I'll try and find time.

I think if arkmanager.cfg becomes editable again, and flags can be set there, that's fine. The problem was that you only could provide them as a argument to docker run, which got tricky.

So I'm happy with anything that isn't that :)
