### ISSUE TITLE
exec not found - Cannot start ARK server

### ISSUE THREAD

**Issue by Julicraft44** [Hermsi1337/docker-ark-server#45]
Hi there.

I am trying to setup a normal ARK server with this docker image but the container is continuously restarting with the following error:

`Error! App '376030' state is 0x202 after update job.
No crontab set
Running command 'run' for instance 'main'
[  WARN  ] 	Your ARK server exec could not be found.
2022-04-08 21:04:46: start
2022-04-08 21:04:46: Running /app/server/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?SessionName=ARKServer\?ServerPassword=GamePassword\?ServerAdminPassword=MyPassword\?MaxPlayers=10\?GameModIds\?GameModIds\?Port=7778\?QueryPort=27015\?RCONEnabled=True\?RCONPort=27020\?listen -log -log
/usr/local/bin/arkmanager: line 1319: /app/server/ShooterGame/Binaries/Linux/ShooterGameServer: No such file or directory
2022-04-08 21:04:46: Server PID: 87`

How can I fix this issue? Seems like a file is missing...

Thanks for any help

**Comment by Hermsi1337** [comment]
Hey @Julicraft44, could you provide some information regarding you setup?

Are you using `docker-compose`? If so, please share your `docker-compose.yml`.

Ty!

**Comment by Julicraft44** [comment]
Hi @Hermsi1337 
I am using Portainer to setup the server but i think it's using docker-compose, too.
The file should be something like this: 
`
version: '3'

services:
  server:
    restart: always
    container_name: ARK_Server
    image: hermsi/ark-server:latest
    volumes:
      - ARK_app:/app
      - ARK_backup:/home/steam/ARK-Backups
    environment:
      - SESSION_NAME=ARK_Server
      - SERVER_MAP=TheIsland
      - SERVER_PASSWORD=securePassword
      - ADMIN_PASSWORD=verySecurePassword
      - MAX_PLAYERS=10
      - UPDATE_ON_START=true
      - BACKUP_ON_STOP=true
      - GAME_CLIENT_PORT=7778
      - UDP_SOCKET_PORT=7779
    ports:
      - "7778:7778/udp"
      - "7779:7779/udp"
      - "27020:27020/tcp"
      - "27015:27015/udp"
`

**Comment by Hermsi1337** [comment]
@halkeye was also using portainer along with this image.   
Do you have the time to look at this issue @halkeye ? Unfortunately I'M not very firm with portainer )= 

@Julicraft44 it looks like the initial install was not successfull / complete. Did you already try a complete re-install?

**Comment by Julicraft44** [comment]
Yeah. I tried to re-install it several times but I got the same error every time.
I will try it without portainer and on another machine when I have time.

**Comment by halkeye** [comment]
There's really no real difference between portainer and docker compose

We decided to move onto a new game around the time of the rewrite 

Isnt there an env flag you can see that enables bash debug mode and you can see the commands being run?

**Comment by Hermsi1337** [comment]
@Julicraft44 could you set `DEBUG=true` and the do a re-install please?

Then, provide logs from the very first startup (=

**Comment by Winor** [comment]
``Error! App '376030' state is 0x202 ``
202 is the out of space error. Are you sure you have enough drive space for it? I think the server requires at least 20GB.

**Comment by Julicraft44** [comment]
@Hermsi1337 Here is the log that I am getting from portainer: [Pastebin](https://pastebin.com/4BKcPryB)
@Winor I should have enough space left.

**Comment by Likqez** [comment]
I recently set up my server using portainer too. There should not be any issue directly from portainer. If you suspect an error from portainer, try adding the stack with the ``docker stack`` command and the compose file directly.

But because it is containerized, the issue needs to occure on your system only.

My tip is to first check your partition errors. :)

### My setup:
[compose File](https://gist.github.com/Likqez/6d3924bbb263a27a5a6af07075d7092b)
I am utilizing portainers stack env management system, which will replace the placeholders in my stack file.
![portainer env](https://user-images.githubusercontent.com/41593553/163656746-5d7458dd-e309-4078-b3ea-fc196239e505.png)

Hope this helps!

**Comment by Hermsi1337** [comment]
I've also did some research on this. And it seems like @Winor is correct: You're definitely out of disk space.

https://steamcommunity.com/app/232090/discussions/0/1694923613855424284/#c1694923613855617478

Unfortunately I'm unable to give you any advice on your disks since im not very familiar with portainer ):

**Comment by Julicraft44** [comment]
Alright. Thanks for the help and quick responses. I will check my disk again. 

Just an idea, but you could catch this error and make a error message out of it so it's easier to understand the error(especially when you new to docker)

**Comment by Likqez** [comment]
If you are talking about the first error, it should not be caused by portainer or docker itself.
The log from your original post, tells: 

> No such file or directory 

Could you share a screenshot of the ``server/ShooterGame/Binaries/Linux`` directory, because it seems like it's missing the executable ``ShooterGameServer``

Isn't there information missing in your shared docker stack file?
Would you mind sharing the full version as a [gist](https://gist.github.com/)?
